package com.example.thumbs_upapp;

import java.io.Serializable;

public class TestMessagePackage implements Serializable {
    public String preferHand = "";
    public int lastTestNum = 0;
    public long timer1 = 0;
    public double accuracy1 = 1.0;
    public double preference1 = 1.0;
    public long timer2 = 0;
    public double accuracy2 = 1.0;
    public double preference2 = 1.0;
    public long timer3 = 0;
    public double accuracy3 = 1.0;
    public double preference3 = 1.0;
    public long timer4 = 0;
    public double accuracy4 = 1.0;
    public double preference4 = 1.0;
    public long timer5 = 0;
    public double accuracy5 = 1.0;
    public double preference5 = 1.0;
    public long timer6 = 0;
    public double accuracy6 = 1.0;
    public double preference6 = 1.0;
    public long timer7 = 0;
    public double accuracy7 = 1.0;
    public double preference7 = 1.0;
    public long timer8 = 0;
    public double accuracy8 = 1.0;
    public double preference8 = 1.0;

    public String getCSVlog() {
        StringBuilder str = new StringBuilder();
        str.append("1,");
        str.append(timer1);
        str.append(",");
        str.append(accuracy1);
        str.append(",");
        str.append(preference1);
        str.append("\n");
        str.append("2,");
        str.append(timer2);
        str.append(",");
        str.append(accuracy2);
        str.append(",");
        str.append(preference2);
        str.append("\n");
        str.append("3,");
        str.append(timer3);
        str.append(",");
        str.append(accuracy3);
        str.append(",");
        str.append(preference3);
        str.append("\n");
        str.append("4,");
        str.append(timer4);
        str.append(",");
        str.append(accuracy4);
        str.append(",");
        str.append(preference4);
        str.append("\n");
        str.append("5,");
        str.append(timer5);
        str.append(",");
        str.append(accuracy5);
        str.append(",");
        str.append(preference5);
        str.append("\n");
        str.append("6,");
        str.append(timer6);
        str.append(",");
        str.append(accuracy6);
        str.append(",");
        str.append(preference6);
        str.append("\n");
        str.append("7,");
        str.append(timer7);
        str.append(",");
        str.append(accuracy7);
        str.append(",");
        str.append(preference7);
        str.append("\n");
        str.append("8,");
        str.append(timer8);
        str.append(",");
        str.append(accuracy8);
        str.append(",");
        str.append(preference8);
        str.append("\n");
        str.append("\n");
        return str.toString();
    }
}
